site_name: DRE<sup>4</sup>M
nav:
  - Home: index.md
  - Input: input.md
  - About: about.md
  - Model: model.md
  - License: license.md
theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Argonne National Laboratory - 2023, written by D. Thierry.
